### ISSUE TITLE
Does this cucumber-chai-wd work with should?

### ISSUE THREAD

**Issue by jlin412** [sebsorin/cucumber-chai-wd#3]
Does it only work with expect?  Or should as well?
If should does not work, can we support that?

**Comment by sebsorin** [comment]
No it does not support that but it will be an interesting feature

**Comment by jlin412** [comment]
+++++++++++++++1

**Comment by sebsorin** [comment]
Should support has been published in 0.2.0 release

**Comment by jlin412** [comment]
Great!!! Is there anything additional that we need to do to use should?

**Comment by sebsorin** [comment]
No, nothing additional. Actually I have overriden chai.Assertion class so now expect, should and assert are serialized in control flow.

**Comment by jlin412** [comment]
@sebsorin When we try to use it, we are getting error.
I tried it to require the following in protractor:

```
//chai
var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
global.expect = chai.expect;
global.assert = chai.assert;
chai.should();
Object.defineProperty(protractor.promise.Promise.prototype, 'should', {
  get: Object.prototype.__lookupGetter__('should'),
  set: Object.prototype.__lookupSetter__('should')
});

this.chai = chai;
require('cucumber-chai-wd').use(this);
```

It looks like that it doesn't know about chai as promise:

```
1) Scenario: Error icon, banner and prev/next error buttons on all days having errors - hourly user - test/e2e/features/time/timecard/time_entry_errors.feature:7
   Step: Then I should see error icon and banner on all days with errors - test/e2e/features/time/timecard/time_entry_errors.feature:25
   Step Definition: test/e2e/features/time/step_definitions/timecard_steps.js:682
   Message:
     TypeError: Cannot read property 'eventually' of undefined
         at World.<anonymous> (/Users/linj/redbox_spa/redbox_angular/test/e2e/features/time/step_definitions/timecard_steps.js:683:60)
         at nextTickCallbackWith0Args (node.js:420:9)
         at process._tickCallback (node.js:349:13)

2) Scenario: estimate data on days with errors and cancel modal and save - hourly user - test/e2e/features/time/timecard/time_entry_errors.feature:29
   Step: Then I should see error icon on that day - test/e2e/features/time/timecard/time_entry_errors.feature:39
   Step Definition: test/e2e/features/time/step_definitions/timecard_steps.js:707
   Message:
     TypeError: Cannot read property 'be' of undefined
         at World.<anonymous> (/Users/linj/redbox_spa/redbox_angular/test/e2e/features/time/step_definitions/timecard_steps.js:708:88)
         at nextTickCallbackWith0Args (node.js:420:9)
         at process._tickCallback (node.js:349:13)

3) Scenario: ted 500 errors - test/e2e/features/time/timecard/time_entry_errors.feature:51
   Step: Then I should see adp banner error on timecard - test/e2e/features/time/timecard/time_entry_errors.feature:55
   Step Definition: test/e2e/features/time/step_definitions/timecard_steps.js:979
   Message:
     TypeError: calendarTimecardPage.adpAlertError.isDisplayed(...).should.become is not a function
         at World.<anonymous> (/Users/linj/redbox_spa/redbox_angular/test/e2e/features/time/step_definitions/timecard_steps.js:980:61)
         at nextTickCallbackWith0Args (node.js:420:9)
         at process._tickCallback (node.js:349:13)
```
